version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: challenge2-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tech123
      POSTGRES_DB: challenge2
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  node:
    build: .
    container_name: challenge2-node
    ports:
      - "3001:3001"
    environment:
      environment:
        - DATABASE_HOST=postgres
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=tech123
        - DATABASE_NAME=challenge2
        - DATABASE_PORT=5432
    depends_on:
      - postgres

volumes:
  pgdata:
