services:
  # Postgres service
  postgres:
    image: postgres:latest
    container_name: challenge2-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tech123
      POSTGRES_DB: challenge2
    ports:
      - "5434:5432"
    networks:
      - challenge_network

  # Node.js service (back-end)
  node:
    build: .
    container_name: challenge2-node
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=tech123
      - DB_NAME=challenge2
    depends_on:
      - postgres
    networks:
      - challenge_network

  # React service (front-end)
  # react:
  #   build:
  #     context: ../blog-frontend
  #     dockerfile: Dockerfile
  #   container_name: challenge2-front
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   depends_on:
  #     - node
  #   networks:
  #     - challenge_network
  #   volumes:
  #     - ../blog-frontend:/app

networks:
  challenge_network:
